In [297]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/binib1997/superstore/Superstore.csv
/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTrain.csv
/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTest.csv
/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv
/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv
/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv

In [298]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# import datasets on a dataframe

In [299]:
store = pd.read_csv('/kaggle/input/datasets/binib1997/superstore/Superstore.csv', encoding='latin-1')
titanic = pd.read_csv('/kaggle/input/datasets/lovishbansal123/titanic-dataset/Titanic-Dataset.csv')
iris = pd.read_csv('/kaggle/input/datasets/himanshunakrani/iris-dataset/iris.csv')
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')
climate = pd.read_csv('/kaggle/input/datasets/sumanthvrao/daily-climate-time-series-data/DailyDelhiClimateTrain.csv')

# Series

# 1. Create a series from a list

In [300]:
np_arr = (np.random.random(5) * 20).astype(np.int8)

print(f"Series from np array: {pd.Series(np_arr)}")
print(f"Series from py array: {pd.Series(np_arr.tolist())}")

Series from np array: 0     3
1     8
2    14
3    19
4    17
dtype: int8
Series from py array: 0     3
1     8
2    14
3    19
4    17
dtype: int64

# 2. Create series from a dictionary

In [301]:
py_dict = {
    "Burger": 298,
    "Pizza": 680,
    "Coke": 25,
    "Milk Shake": 180
}

pd_series = pd.Series(py_dict)
pd_series.name = "Product Menu"
pd_series

Burger        298
Pizza         680
Coke           25
Milk Shake    180
Name: Product Menu, dtype: int64

# 3. Create a series from dataframe

In [302]:
product_sales_series = store['Sales']
product_sales_series

0       261.9600
1       731.9400
2        14.6200
3       957.5775
4        22.3680
          ...
9989     25.2480
9990     91.9600
9991    258.5760
9992     29.6000
9993    243.1600
Name: Sales, Length: 9994, dtype: float64

# 4. Apply below operations on a series to understand about a series

In [303]:
# head
print(f"Head: {product_sales_series.head()}")
# tail
print(f"Tail: {product_sales_series.tail()}")
# sample
print(f"Sample: {product_sales_series.sample()}")
# size
print(f"Tail: {product_sales_series.size}")
# dtype
print(f"Data Type: {product_sales_series.dtype}")
# astype
print(f"Data Type: {product_sales_series.astype(int)}")
# index
print(f"Index: {product_sales_series.index}")
# values
print(f"Values: {product_sales_series.values}")

Head: 0    261.9600
1    731.9400
2     14.6200
3    957.5775
4     22.3680
Name: Sales, dtype: float64
Tail: 9989     25.248
9990     91.960
9991    258.576
9992     29.600
9993    243.160
Name: Sales, dtype: float64
Sample: 9283    11.696
Name: Sales, dtype: float64
Tail: 9994
Data Type: float64
Data Type: 0       261
1       731
2        14
3       957
4        22
       ...
9989     25
9990     91
9991    258
9992     29
9993    243
Name: Sales, Length: 9994, dtype: int64
Index: RangeIndex(start=0, stop=9994, step=1)
Values: [261.96  731.94   14.62  ... 258.576  29.6   243.16 ]

# 5. Change data-type of a series

In [304]:
product_sales_series.astype(str)

0         261.96
1         731.94
2          14.62
3       957.5775
4         22.368
          ...
9989      25.248
9990       91.96
9991     258.576
9992        29.6
9993      243.16
Name: Sales, Length: 9994, dtype: object

# 6. Apply below mathematical operations on a series

In [305]:
# count
print(f"Count: {product_sales_series.count()}")
# sum
print(f"Sum: {product_sales_series.sum()}")
# product
print(f"Product of top 9: ", product_sales_series[0:9].prod())
# min
print(f"Min: {product_sales_series.min()}")
# max
print(f"Max: {product_sales_series.max()}")
# mean
print(f"Max: {product_sales_series.max()}")
# median
print(f"Median: {product_sales_series.median()}")
# mode
print(f"Mode: {product_sales_series.mode()}")
# describe
print(f"Describe: {product_sales_series.describe()}")
# std
print(f"Standard Deviation: {product_sales_series.std()}")
# var
print(f"Variance: {product_sales_series.var()}")

Count: 9994
Sum: 2297200.8603000003
Product of top 9:  3.585002371035412e+17
Min: 0.444
Max: 22638.48
Max: 22638.48
Median: 54.489999999999995
Mode: 0    12.96
Name: Sales, dtype: float64
Describe: count     9994.000000
mean       229.858001
std        623.245101
min          0.444000
25%         17.280000
50%         54.490000
75%        209.940000
max      22638.480000
Name: Sales, dtype: float64
Standard Deviation: 623.2451005086818
Variance: 388434.45530807687

# 7. Do 3 slicing operations on a series

In [306]:
store_product_data = store[['Order ID', 'Sales', 'Profit']].sort_values(by='Profit', ascending=False)[:5]
store_product_data

            Order ID     Sales     Profit
6826  CA-2016-118689  17499.95  8399.9760
8153  CA-2017-140151  13999.96  6719.9808
4190  CA-2017-166709  10499.97  5039.9856
9039  CA-2016-117121   9892.74  4946.3700
4098  CA-2014-116904   9449.95  4630.4755

In [307]:
store_product_data = store_product_data[::2].sort_values(by='Sales', ascending=False)
store_product_data

            Order ID     Sales     Profit
6826  CA-2016-118689  17499.95  8399.9760
4190  CA-2017-166709  10499.97  5039.9856
4098  CA-2014-116904   9449.95  4630.4755

In [308]:
store_product_data = store_product_data[:1:1]
store_product_data

            Order ID     Sales    Profit
6826  CA-2016-118689  17499.95  8399.976

# Dataframe

# 1. Create a dataframe from a list

In [309]:
mark_sheet = (np.random.random((3, 3)) * 100).astype(np.int8)
subjects = ["English", "Math", "Science"]
my_df = pd.DataFrame(mark_sheet, columns=subjects)
my_df

   English  Math  Science
0       34    62       85
1       43    95       39
2       22    15       57

# 2. Apply below dataframe understanding operations

In [310]:
# head
my_df.head()

   English  Math  Science
0       34    62       85
1       43    95       39
2       22    15       57

In [311]:
# tail
my_df.tail()

   English  Math  Science
0       34    62       85
1       43    95       39
2       22    15       57

In [312]:
# sample
my_df.sample()

   English  Math  Science
1       43    95       39

In [313]:
# info
my_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   English  3 non-null      int8
 1   Math     3 non-null      int8
 2   Science  3 non-null      int8
dtypes: int8(3)
memory usage: 141.0 bytes

In [314]:
# isnull
my_df.isnull()

   English   Math  Science
0    False  False    False
1    False  False    False
2    False  False    False

In [315]:
# duplicated
my_df.duplicated()

0    False
1    False
2    False
dtype: bool

# 2. Apply below dataframe attribute operations

In [316]:
# shape
my_df.shape

(3, 3)

In [317]:
# dtypes
my_df.dtypes

English    int8
Math       int8
Science    int8
dtype: object

In [318]:
# columns
my_df.columns

Index(['English', 'Math', 'Science'], dtype='object')

In [319]:
# values
my_df.values

array([[34, 62, 85],
       [43, 95, 39],
       [22, 15, 57]], dtype=int8)

# 3. Apply below mathematical operations on a feature taken from dataframe

In [320]:
# count
my_df['Math'].count()

np.int64(3)

In [321]:
# sum
my_df['Math'].sum()

np.int64(172)

In [322]:
# product
my_df['Math'].product()

np.int64(88350)

In [323]:
# min
my_df['Math'].min()

np.int8(15)

In [324]:
# max
my_df['Math'].max()

np.int8(95)

In [325]:
# mean
my_df['Math'].mean()

np.float64(57.333333333333336)

In [326]:
# median
my_df['Math'].median()

np.float64(62.0)

In [327]:
# mode
my_df['Math'].mode()

0    15
1    62
2    95
Name: Math, dtype: int8

In [328]:
# describe
my_df['Math'].describe()

count     3.000000
mean     57.333333
std      40.203648
min      15.000000
25%      38.500000
50%      62.000000
75%      78.500000
max      95.000000
Name: Math, dtype: float64

In [329]:
# std
my_df['Math'].std()

np.float64(40.20364825899925)

In [330]:
# var
my_df['Math'].var()

np.float64(1616.3333333333335)

# Selection and filtering

In [331]:
# loc
tips.loc[13: 26, ['sex', 'tip']]

       sex   tip
13    Male  3.00
14  Female  3.02
15    Male  3.92
16  Female  1.67
17    Male  3.71
18  Female  3.50
19    Male  3.35
20    Male  4.08
21  Female  2.75
22  Female  2.23
23    Male  7.58
24    Male  3.18
25    Male  2.34
26    Male  2.00

In [332]:
# iloc
tips.iloc[13: 26, :6:2]

    total_bill     sex  day
13       18.43    Male  Sun
14       14.83  Female  Sun
15       21.58    Male  Sun
16       10.33  Female  Sun
17       16.29    Male  Sun
18       16.97  Female  Sun
19       20.65    Male  Sat
20       17.92    Male  Sat
21       20.29  Female  Sat
22       15.77  Female  Sat
23       39.42    Male  Sat
24       19.82    Male  Sat
25       17.81    Male  Sat

In [333]:
# isin()
tips[tips['sex'].isin(['Male'])]

     total_bill   tip   sex smoker  day    time  size
1         10.34  1.66  Male     No  Sun  Dinner     3
2         21.01  3.50  Male     No  Sun  Dinner     3
3         23.68  3.31  Male     No  Sun  Dinner     2
5         25.29  4.71  Male     No  Sun  Dinner     4
6          8.77  2.00  Male     No  Sun  Dinner     2
..          ...   ...   ...    ...  ...     ...   ...
236       12.60  1.00  Male    Yes  Sat  Dinner     2
237       32.83  1.17  Male    Yes  Sat  Dinner     2
239       29.03  5.92  Male     No  Sat  Dinner     3
241       22.67  2.00  Male    Yes  Sat  Dinner     2
242       17.82  1.75  Male     No  Sat  Dinner     2

[157 rows x 7 columns]

In [334]:
# logical operation (&, |, ~)
best_days_for_tip_df = tips[tips['day'].isin(tips['day'].value_counts().index) & tips['time'].isin(['Dinner'])].groupby('day')['tip'].mean().nlargest(1)
print(f"Never miss work on {best_days_for_tip_df.index[0]} to get the best tips")

Never miss work on Sun to get the best tips

# 1. Select 11-20th rows and total_bill and tip columns from tips dataframe

In [335]:
tips.loc[11: 20, ['total_bill', 'tip']]

    total_bill   tip
11       35.26  5.00
12       15.42  1.57
13       18.43  3.00
14       14.83  3.02
15       21.58  3.92
16       10.33  1.67
17       16.29  3.71
18       16.97  3.50
19       20.65  3.35
20       17.92  4.08

# 2. Select 0-20th rows and total_bill, tip and day columns from tips dataframe

In [336]:
tips.loc[: 20, ['total_bill', 'tip']]

    total_bill   tip
0        16.99  1.01
1        10.34  1.66
2        21.01  3.50
3        23.68  3.31
4        24.59  3.61
5        25.29  4.71
6         8.77  2.00
7        26.88  3.12
8        15.04  1.96
9        14.78  3.23
10       10.27  1.71
11       35.26  5.00
12       15.42  1.57
13       18.43  3.00
14       14.83  3.02
15       21.58  3.92
16       10.33  1.67
17       16.29  3.71
18       16.97  3.50
19       20.65  3.35
20       17.92  4.08

# 3. Select customers who comes in sunday and total_bill is greater than 20 dollars

In [337]:
tips[(tips['day'] == 'Sun') & (tips['total_bill'] > 20)]

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
11        35.26  5.00  Female     No  Sun  Dinner     4
15        21.58  3.92    Male     No  Sun  Dinner     2
44        30.40  5.60    Male     No  Sun  Dinner     4
46        22.23  5.00    Male     No  Sun  Dinner     2
47        32.40  6.00    Male     No  Sun  Dinner     4
48        28.55  2.05    Male     No  Sun  Dinner     3
52        34.81  5.20  Female     No  Sun  Dinner     4
54        25.56  4.34    Male     No  Sun  Dinner     4
112       38.07  4.00    Male     No  Sun  Dinner     3
113       23.95  2.55    Male     No  Sun  Dinner     2
114       25.71  4.00  Female     No  Sun  Dinner     3
116       29.93  5.07    Male     No  Sun  Dinner     4
153       24.55  2.00    Male     No  Sun  Dinner     4
155       29.85  5.14  Female     No  Sun  Dinner     5
156       48.17  5.00    Male     No  Sun  Dinner     6
157       25.00  3.75  Female     No  Sun  Dinner     4
160       21.50  3.50    Male     No  Sun  Dinner     4
165       24.52  3.48    Male     No  Sun  Dinner     3
166       20.76  2.24    Male     No  Sun  Dinner     2
167       31.71  4.50    Male     No  Sun  Dinner     4
173       31.85  3.18    Male    Yes  Sun  Dinner     2
175       32.90  3.11    Male    Yes  Sun  Dinner     2
179       34.63  3.55    Male    Yes  Sun  Dinner     2
180       34.65  3.68    Male    Yes  Sun  Dinner     4
181       23.33  5.65    Male    Yes  Sun  Dinner     2
182       45.35  3.50    Male    Yes  Sun  Dinner     3
183       23.17  6.50    Male    Yes  Sun  Dinner     4
184       40.55  3.00    Male    Yes  Sun  Dinner     2
185       20.69  5.00    Male     No  Sun  Dinner     5
186       20.90  3.50  Female    Yes  Sun  Dinner     3
187       30.46  2.00    Male    Yes  Sun  Dinner     5
189       23.10  4.00    Male    Yes  Sun  Dinner     3

# 4. Select passengers who are male and age greater than 50 from titanic

In [338]:
titanic[(titanic['Sex'] == 'male') & (titanic['Age'] > 50)]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
94,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
124,125,0,1,"White, Mr. Percival Wayland",male,54.0,0,1,35281,77.2875,D26,S
150,151,0,2,"Bateman, Rev. Robert James",male,51.0,0,0,S.O.P. 1166,12.5250,NaN,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
174,175,0,1,"Smith, Mr. James Clinch",male,56.0,0,0,17764,30.6958,A7,C
222,223,0,3,"Green, Mr. George Henry",male,51.0,0,0,21440,8.0500,NaN,S
232,233,0,2,"Sjostedt, Mr. Ernst Adolf",male,59.0,0,0,237442,13.5000,NaN,S
249,250,0,2,"Carter, Rev. Ernest Courtenay",male,54.0,1,0,244252,26.0000,NaN,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
262,263,0,1,"Taussig, Mr. Emil",male,52.0,1,1,110413,79.6500,E67,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
317,318,0,2,"Moraweck, Dr. Ernest",male,54.0,0,0,29011,14.0000,NaN,S
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
406,407,0,3,"Widegren, Mr. Carl/Charles Peter",male,51.0,0,0,347064,7.7500,NaN,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
449,450,1,1,"Peuchen, Major. Arthur Godfrey",male,52.0,0,0,113786,30.5000,C104,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
467,468,0,1,"Smart, Mr. John Montgomery",male,56.0,0,0,113792,26.5500,NaN,S
487,488,0,1,"Kent, Mr. Edward Austin",male,58.0,0,0,11771,29.7000,B37,C
492,493,0,1,"Molson, Mr. Harry Markland",male,55.0,0,0,113787,30.5000,C30,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
582,583,0,2,"Downton, Mr. William James",male,54.0,0,0,28403,26.0000,NaN,S
587,588,1,1,"Frolicher-Stehli, Mr. Maxmillian",male,60.0,1,1,13567,79.2000,B41,C
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
626,627,0,2,"Kirkland, Rev. Charles Leonard",male,57.0,0,0,219533,12.3500,NaN,Q
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
631,632,0,3,"Lundahl, Mr. Johan Svensson",male,51.0,0,0,347743,7.0542,NaN,S
647,648,1,1,"Simonius-Blumer, Col. Oberst Alfons",male,56.0,0,0,13213,35.5000,A26,C
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.0,0,2,35273,113.2750,D48,C
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
684,685,0,2,"Brown, Mr. Thomas William Solomon",male,60.0,1,1,29750,39.0000,NaN,S
694,695,0,1,"Weir, Col. John",male,60.0,0,0,113800,26.5500,NaN,S
695,696,0,2,"Chapman, Mr. Charles Henry",male,52.0,0,0,248731,13.5000,NaN,S
714,715,0,2,"Greenberg, Mr. Samuel",male,52.0,0,0,250647,13.0000,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S

# 5. Select customers who are female and tip greater than 5 dollars from tips dataframe - write query operation

In [339]:
tips[(tips['sex'] == 'Female') & (tips['tip'] > 5)]

     total_bill   tip     sex smoker   day    time  size
52        34.81  5.20  Female     No   Sun  Dinner     4
85        34.83  5.17  Female     No  Thur   Lunch     4
155       29.85  5.14  Female     No   Sun  Dinner     5
214       28.17  6.50  Female    Yes   Sat  Dinner     3

# groupby

# 1. group on region based in store dataframe

In [340]:
store.groupby('Region')['Order ID'].count().nlargest(1)

Region
West    3203
Name: Order ID, dtype: int64

# 2. Find region-wise average sales

In [341]:
store.groupby('Region')['Sales'].mean()

Region
Central    215.772661
East       238.336110
South      241.803645
West       226.493233
Name: Sales, dtype: float64

# 3. Find region-wise average profit

In [342]:
store.groupby('Region')['Profit'].mean()

Region
Central    17.092709
East       32.135808
South      28.857673
West       33.849032
Name: Profit, dtype: float64

# 4. Find region-wise maximum profit

In [343]:
store.groupby('Region')['Sales'].max()

Region
Central    17499.950
East       11199.968
South      22638.480
West       13999.960
Name: Sales, dtype: float64

# 5. Apply multiple aggregate functions on region-wise sales

In [344]:
store.groupby('Region')['Order ID'].count().nlargest(2)

Region
West    3203
East    2848
Name: Order ID, dtype: int64

# 6. group on region and category wise

In [345]:
store.groupby('Region')['Category'].count()

Region
Central    2323
East       2848
South      1620
West       3203
Name: Category, dtype: int64

# 7. Find region and category wise average sales

In [346]:
store.groupby(['Region', 'Category'])['Sales'].mean()

Region   Category
Central  Furniture          340.534644
         Office Supplies    117.458801
         Technology         405.753124
East     Furniture          346.574383
         Office Supplies    120.044425
         Technology         495.278469
South    Furniture          353.309289
         Office Supplies    126.282727
         Technology         507.753952
West     Furniture          357.302325
         Office Supplies    116.422377
         Technology         420.687533
Name: Sales, dtype: float64

# 8. Find region and category wise average, minimumm, maximum and sum sales

In [347]:
store.groupby(['Region', 'Category'])['Sales'].mean()

Region   Category
Central  Furniture          340.534644
         Office Supplies    117.458801
         Technology         405.753124
East     Furniture          346.574383
         Office Supplies    120.044425
         Technology         495.278469
South    Furniture          353.309289
         Office Supplies    126.282727
         Technology         507.753952
West     Furniture          357.302325
         Office Supplies    116.422377
         Technology         420.687533
Name: Sales, dtype: float64

In [348]:
store.groupby(['Region', 'Category'])['Sales'].max()

Region   Category
Central  Furniture           3504.900
         Office Supplies     9892.740
         Technology         17499.950
East     Furniture           4416.174
         Office Supplies     4663.736
         Technology         11199.968
South    Furniture           4297.644
         Office Supplies     6354.950
         Technology         22638.480
West     Furniture           3610.848
         Office Supplies     8187.650
         Technology         13999.960
Name: Sales, dtype: float64

In [349]:
store.groupby(['Region', 'Category'])['Sales'].min()

Region   Category
Central  Furniture          1.892
         Office Supplies    0.444
         Technology         1.980
East     Furniture          2.960
         Office Supplies    0.852
         Technology         2.970
South    Furniture          2.784
         Office Supplies    1.167
         Technology         1.584
West     Furniture          3.480
         Office Supplies    1.080
         Technology         0.990
Name: Sales, dtype: float64

In [350]:
store.groupby(['Region', 'Category'])['Sales'].sum()

Region   Category
Central  Furniture          163797.1638
         Office Supplies    167026.4150
         Technology         170416.3120
East     Furniture          208291.2040
         Office Supplies    205516.0550
         Technology         264973.9810
South    Furniture          117298.6840
         Office Supplies    125651.3130
         Technology         148771.9080
West     Furniture          252612.7435
         Office Supplies    220853.2490
         Technology         251991.8320
Name: Sales, dtype: float64

# Merging and joining

In [351]:
students = pd.DataFrame({
    "student_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                   111, 112, 113, 114, 115, 116, 117, 118, 119, 120],
    "name": ["Rahim", "Karim", "Hasan", "Sakib", "Nabil",
             "Tanvir", "Fahim", "Rafi", "Imran", "Shakil",
             "Arif", "Jahid", "Mehedi", "Siam", "Tareq",
             "Rakib", "Adnan", "Nayeem", "Foysal", "Rony"],
    "department": ["CSE", "EEE", "CSE", "BBA", "CSE",
                   "EEE", "CSE", "BBA", "CSE", "EEE",
                   "CSE", "BBA", "EEE", "CSE", "BBA",
                   "CSE", "EEE", "CSE", "BBA", "EEE"]
})

students

    student_id    name department
0          101   Rahim        CSE
1          102   Karim        EEE
2          103   Hasan        CSE
3          104   Sakib        BBA
4          105   Nabil        CSE
5          106  Tanvir        EEE
6          107   Fahim        CSE
7          108    Rafi        BBA
8          109   Imran        CSE
9          110  Shakil        EEE
10         111    Arif        CSE
11         112   Jahid        BBA
12         113  Mehedi        EEE
13         114    Siam        CSE
14         115   Tareq        BBA
15         116   Rakib        CSE
16         117   Adnan        EEE
17         118  Nayeem        CSE
18         119  Foysal        BBA
19         120    Rony        EEE

In [352]:
results = pd.DataFrame({
    "student_id": [101, 102, 103, 105, 106, 108, 109, 111, 112, 114,
                   121, 122, 123, 124, 125, 126, 127, 128, 129, 130],
    "math": [85, 72, 91, 68, 77, 88, 74, 95, 81, 69,
             78, 84, 92, 73, 89, 67, 80, 94, 76, 83],
    "python": [90, 75, 88, 72, 80, 92, 79, 96, 85, 71,
               82, 87, 95, 76, 91, 70, 84, 93, 78, 86]
})

results

    student_id  math  python
0          101    85      90
1          102    72      75
2          103    91      88
3          105    68      72
4          106    77      80
5          108    88      92
6          109    74      79
7          111    95      96
8          112    81      85
9          114    69      71
10         121    78      82
11         122    84      87
12         123    92      95
13         124    73      76
14         125    89      91
15         126    67      70
16         127    80      84
17         128    94      93
18         129    76      78
19         130    83      86

In [353]:
departments = pd.DataFrame({
    "dept_id": [1, 2, 3, 4],
    "department": [
        "CSE",
        "EEE",
        "BBA",
        "Civil"
    ],
    "faculty": [
        "Engineering",
        "Engineering",
        "Business",
        "Engineering"
    ]
})

departments

   dept_id department      faculty
0        1        CSE  Engineering
1        2        EEE  Engineering
2        3        BBA     Business
3        4      Civil  Engineering

# 1. Create a dataframe contains students name,faculty and number on math and python

In [354]:
merged_table = pd.merge(
    pd.merge(
        students,
        departments,
        left_on='department',
        right_on='department',
        how='inner'
    ),
    results,
    left_on='student_id',
    right_on='student_id',
    how='left'
)

merged_table[['name', 'faculty', 'math', 'python']]

      name      faculty  math  python
0    Rahim  Engineering  85.0    90.0
1    Karim  Engineering  72.0    75.0
2    Hasan  Engineering  91.0    88.0
3    Sakib     Business   NaN     NaN
4    Nabil  Engineering  68.0    72.0
5   Tanvir  Engineering  77.0    80.0
6    Fahim  Engineering   NaN     NaN
7     Rafi     Business  88.0    92.0
8    Imran  Engineering  74.0    79.0
9   Shakil  Engineering   NaN     NaN
10    Arif  Engineering  95.0    96.0
11   Jahid     Business  81.0    85.0
12  Mehedi  Engineering   NaN     NaN
13    Siam  Engineering  69.0    71.0
14   Tareq     Business   NaN     NaN
15   Rakib  Engineering   NaN     NaN
16   Adnan  Engineering   NaN     NaN
17  Nayeem  Engineering   NaN     NaN
18  Foysal     Business   NaN     NaN
19    Rony  Engineering   NaN     NaN

# 2. Department wise students count

In [355]:
merged_table[['name', 'faculty']]

      name      faculty
0    Rahim  Engineering
1    Karim  Engineering
2    Hasan  Engineering
3    Sakib     Business
4    Nabil  Engineering
5   Tanvir  Engineering
6    Fahim  Engineering
7     Rafi     Business
8    Imran  Engineering
9   Shakil  Engineering
10    Arif  Engineering
11   Jahid     Business
12  Mehedi  Engineering
13    Siam  Engineering
14   Tareq     Business
15   Rakib  Engineering
16   Adnan  Engineering
17  Nayeem  Engineering
18  Foysal     Business
19    Rony  Engineering

# 3. Faculty wise department count

In [356]:
merged_table[['name', 'faculty']].groupby('faculty').count()

             name
faculty
Business        5
Engineering    15

# 4. Find department wise highest number on each subject

In [357]:
merged_table[['name', 'department', 'math']].groupby('department').max(['math'])

            math
department
BBA         88.0
CSE         95.0
EEE         77.0

In [358]:
merged_table[['name', 'department', 'python']].groupby('department').max(['python'])

            python
department
BBA           92.0
CSE           96.0
EEE           80.0

In [359]:
merged_table[['name', 'department', 'math', 'python']].groupby('department').max(['math', 'python'])

            math  python
department
BBA         88.0    92.0
CSE         95.0    96.0
EEE         77.0    80.0

# 5. Find faculty wise highest number on each subject

In [360]:
merged_table[['name', 'faculty', 'math', 'python']].groupby('faculty').max(['math', 'python'])

             math  python
faculty
Business     88.0    92.0
Engineering  95.0    96.0

# Time-series

In [361]:
# use climate dataset
climate

            date   meantemp    humidity  wind_speed  meanpressure
0     2013-01-01  10.000000   84.500000    0.000000   1015.666667
1     2013-01-02   7.400000   92.000000    2.980000   1017.800000
2     2013-01-03   7.166667   87.000000    4.633333   1018.666667
3     2013-01-04   8.666667   71.333333    1.233333   1017.166667
4     2013-01-05   6.000000   86.833333    3.700000   1016.500000
...          ...        ...         ...         ...           ...
1457  2016-12-28  17.217391   68.043478    3.547826   1015.565217
1458  2016-12-29  15.238095   87.857143    6.000000   1016.904762
1459  2016-12-30  14.095238   89.666667    6.266667   1017.904762
1460  2016-12-31  15.052632   87.000000    7.325000   1016.100000
1461  2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 5 columns]

# 1. convert time into datetime

In [362]:
date_time_index = pd.to_datetime(climate['date'])
date_time_index

0      2013-01-01
1      2013-01-02
2      2013-01-03
3      2013-01-04
4      2013-01-05
          ...
1457   2016-12-28
1458   2016-12-29
1459   2016-12-30
1460   2016-12-31
1461   2017-01-01
Name: date, Length: 1462, dtype: datetime64[ns]

# 2. set date as index

In [363]:
climate_time_series = climate.copy()
climate_time_series = climate_time_series.set_index(date_time_index)
climate_time_series

                  date   meantemp    humidity  wind_speed  meanpressure
date
2013-01-01  2013-01-01  10.000000   84.500000    0.000000   1015.666667
2013-01-02  2013-01-02   7.400000   92.000000    2.980000   1017.800000
2013-01-03  2013-01-03   7.166667   87.000000    4.633333   1018.666667
2013-01-04  2013-01-04   8.666667   71.333333    1.233333   1017.166667
2013-01-05  2013-01-05   6.000000   86.833333    3.700000   1016.500000
...                ...        ...         ...         ...           ...
2016-12-28  2016-12-28  17.217391   68.043478    3.547826   1015.565217
2016-12-29  2016-12-29  15.238095   87.857143    6.000000   1016.904762
2016-12-30  2016-12-30  14.095238   89.666667    6.266667   1017.904762
2016-12-31  2016-12-31  15.052632   87.000000    7.325000   1016.100000
2017-01-01  2017-01-01  10.000000  100.000000    0.000000   1016.000000

[1462 rows x 5 columns]

# 3. Select row of 13 january, 2015

In [364]:
climate_time_series.loc[['2015-01-13']]

                  date  meantemp  humidity  wind_speed  meanpressure
date
2015-01-13  2015-01-13     12.25    77.875       4.875      1017.125

# 4. Select rows contains in april 2017

In [365]:
climate_time_series.loc[['2017']]

                  date  meantemp  humidity  wind_speed  meanpressure
date
2017-01-01  2017-01-01      10.0     100.0         0.0        1016.0

# 5. Select rows from 11 september, 2014 to 25 september, 2014

In [366]:
climate_time_series.loc['2015-09-11':'2015-09-25']

                  date   meantemp   humidity  wind_speed  meanpressure
date
2015-09-11  2015-09-11  30.750000  49.750000    6.012500   1006.250000
2015-09-12  2015-09-12  32.142857  54.428571    3.171429   1006.000000
2015-09-13  2015-09-13  32.125000  55.250000    1.387500   1005.875000
2015-09-14  2015-09-14  31.875000  54.375000    2.550000   1003.625000
2015-09-15  2015-09-15  33.000000  55.000000    0.462500   1003.250000
2015-09-16  2015-09-16  32.375000  55.000000    1.400000   1003.625000
2015-09-17  2015-09-17  31.375000  58.375000    1.162500   1004.375000
2015-09-18  2015-09-18  31.000000  67.625000    7.412500   1005.125000
2015-09-19  2015-09-19  30.625000  74.250000    2.087500   1003.625000
2015-09-20  2015-09-20  29.142857  69.142857    5.557143   1002.857143
2015-09-21  2015-09-21  30.125000  64.500000    5.800000   1002.500000
2015-09-22  2015-09-22  30.250000  64.375000   10.187500   1002.500000
2015-09-23  2015-09-23  28.625000  61.250000   13.675000   1006.375000
2015-09-24  2015-09-24  28.250000  52.375000   11.575000   1004.625000
2015-09-25  2015-09-25  28.500000  49.375000    8.575000   1003.750000

# 6. Calculate month-wise average windspeed

In [367]:
climate_time_series.groupby(climate_time_series.index.month).mean('meanpressure')[['meanpressure']]

      meanpressure
date
1      1018.152410
2      1015.349232
3      1066.531388
4      1006.975741
5      1001.975698
6       997.878522
7       998.040354
8       984.358104
9      1007.465067
10     1010.509337
11     1009.035227
12     1016.559211

# 7. Calculate month-wise highest meantemp

In [368]:
climate_time_series.groupby(climate_time_series.index.month).max('meantemp')[['meanpressure']]

      meanpressure
date
1      1023.000000
2      1022.000000
3      7679.333333
4      1013.875000
5      1008.375000
6      1004.625000
7      1004.625000
8      1006.200000
9      1352.615385
10     1017.807692
11     1350.296296
12     1022.125000

# 8. Year-wise maximum, minimum and average humidity

In [369]:
climate_time_series.groupby(climate_time_series.index.year).max('humidity')[['humidity']]

        humidity
date
2013   94.000000
2014   96.857143
2015   98.000000
2016   94.300000
2017  100.000000

In [370]:
climate_time_series.groupby(climate_time_series.index.year).min('humidity')[['humidity']]

        humidity
date
2013   15.857143
2014   20.875000
2015   13.428571
2016   18.466667
2017  100.000000

In [371]:
climate_time_series.groupby(climate_time_series.index.year).mean('humidity')[['humidity']]

        humidity
date
2013   63.046292
2014   59.767942
2015   61.430490
2016   58.740174
2017  100.000000

# 9. A new column contains previous 10 days average meantemp

In [418]:
import numpy as np

step_len = 10

list_len = len(climate_time_series)
data_table = climate_time_series.copy()

# Initialize the new column
data_table['avg_10_days_meanpressure'] = 0.0

# Use range(start, stop, step) to automatically jump by 10s
for index in range(0, list_len, step_len):
    # Calculate the mean (now a single float value)
    mean_val = climate_time_series['meanpressure'].iloc[index : index + step_len].mean()
    
    # Assign that single float to all rows in the 10-row slice
    data_table.iloc[index : index + step_len, data_table.columns.get_loc('avg_10_days_meanpressure')] = mean_val

# View the result
data_table.head(20)

,date,meantemp,humidity,wind_speed,meanpressure,avg_10_days_meanpressure
date,,,,,,
2013-01-01,2013-01-01,10.000000,84.500000,0.000000,1015.666667,1017.518095
2013-01-02,2013-01-02,7.400000,92.000000,2.980000,1017.800000,1017.518095
2013-01-03,2013-01-03,7.166667,87.000000,4.633333,1018.666667,1017.518095
2013-01-04,2013-01-04,8.666667,71.333333,1.233333,1017.166667,1017.518095
2013-01-05,2013-01-05,6.000000,86.833333,3.700000,1016.500000,1017.518095
2013-01-06,2013-01-06,7.000000,82.800000,1.480000,1018.000000,1017.518095
2013-01-07,2013-01-07,7.000000,78.600000,6.300000,1020.000000,1017.518095
2013-01-08,2013-01-08,8.857143,63.714286,7.142857,1018.714286,1017.518095
2013-01-09,2013-01-09,14.000000,51.250000,12.500000,1017.000000,1017.518095
2013-01-10,2013-01-10,11.000000,62.000000,7.400000,1015.666667,1017.518095
2013-01-11,2013-01-11,15.714286,51.285714,10.571429,1016.142857,1016.502381
2013-01-12,2013-01-12,14.000000,74.000000,13.228571,1015.571429,1016.502381
2013-01-13,2013-01-13,15.833333,75.166667,4.633333,1013.333333,1016.502381
2013-01-14,2013-01-14,12.833333,88.166667,0.616667,1015.166667,1016.502381
2013-01-15,2013-01-15,14.714286,71.857143,0.528571,1015.857143,1016.502381
2013-01-16,2013-01-16,13.833333,86.666667,0.000000,1016.666667,1016.502381
2013-01-17,2013-01-17,16.500000,80.833333,5.250000,1015.833333,1016.502381
2013-01-18,2013-01-18,13.833333,92.166667,8.950000,1014.500000,1016.502381
2013-01-19,2013-01-19,12.500000,76.666667,5.883333,1021.666667,1016.502381
2013-01-20,2013-01-20,11.285714,75.285714,8.471429,1020.285714,1016.502381